//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zth.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zth.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А.
        /// </summary>
        public static string AmpereUnit {
            get {
                return ResourceManager.GetString("AmpereUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амплитуда тока управления, А.
        /// </summary>
        public static string AmplitudeControlCurrent {
            get {
                return ResourceManager.GetString("AmplitudeControlCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амплитуда греющего тока, А.
        /// </summary>
        public static string AmplitudeHeatingCurrent {
            get {
                return ResourceManager.GetString("AmplitudeHeatingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амплитуда измерительного тока, А.
        /// </summary>
        public static string AmplitudeMeasuringCurrent {
            get {
                return ResourceManager.GetString("AmplitudeMeasuringCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура корпуса А, °С.
        /// </summary>
        public static string AnodeBodyTemperature {
            get {
                return ResourceManager.GetString("AnodeBodyTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t корп. А:.
        /// </summary>
        public static string AnodeBodyTemperatureAbbreviated {
            get {
                return ResourceManager.GetString("AnodeBodyTemperatureAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура охл. А, °С.
        /// </summary>
        public static string AnodeCoolerTemperature {
            get {
                return ResourceManager.GetString("AnodeCoolerTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t охл. А:.
        /// </summary>
        public static string AnodeCoolerTemperatureAbbreviated {
            get {
                return ResourceManager.GetString("AnodeCoolerTemperatureAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биполярный.
        /// </summary>
        public static string Bipolar {
            get {
                return ResourceManager.GetString("Bipolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура корпуса К, °С.
        /// </summary>
        public static string CathodeBodyTemperature {
            get {
                return ResourceManager.GetString("CathodeBodyTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t корп. К:.
        /// </summary>
        public static string CathodeBodyTemperatureAbbreviated {
            get {
                return ResourceManager.GetString("CathodeBodyTemperatureAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура охл. К, °С.
        /// </summary>
        public static string CathodeCoolerTemperature {
            get {
                return ResourceManager.GetString("CathodeCoolerTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t охл. К:.
        /// </summary>
        public static string CathodeCoolerTemperatureAbbreviated {
            get {
                return ResourceManager.GetString("CathodeCoolerTemperatureAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Охлаждение.
        /// </summary>
        public static string Cooling {
            get {
                return ResourceManager.GetString("Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string DegreeCentigradeUnit {
            get {
                return ResourceManager.GetString("DegreeCentigradeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время задержки измерения ТЧП, мкс.
        /// </summary>
        public static string DelayTimeTspMeasurements {
            get {
                return ResourceManager.GetString("DelayTimeTspMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность импульса мощности, с.
        /// </summary>
        public static string DurationPowerPulse {
            get {
                return ResourceManager.GetString("DurationPowerPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только градуировка.
        /// </summary>
        public static string GraduationOnly {
            get {
                return ResourceManager.GetString("GraduationOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Греющий ток.
        /// </summary>
        public static string HeatingCurrent {
            get {
                return ResourceManager.GetString("HeatingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гр. ток:.
        /// </summary>
        public static string HeatingCurrentAbbreviated {
            get {
                return ResourceManager.GetString("HeatingCurrentAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Греющая мощность.
        /// </summary>
        public static string HeatingPower {
            get {
                return ResourceManager.GetString("HeatingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGBT.
        /// </summary>
        public static string IGBT {
            get {
                return ResourceManager.GetString("IGBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мВ.
        /// </summary>
        public static string MegaVoltUnit {
            get {
                return ResourceManager.GetString("MegaVoltUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Односторонее.
        /// </summary>
        public static string OneSided {
            get {
                return ResourceManager.GetString("OneSided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rth Последовательность.
        /// </summary>
        public static string RthSequence {
            get {
                return ResourceManager.GetString("RthSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт нагрев.
        /// </summary>
        public static string StartHeating {
            get {
                return ResourceManager.GetString("StartHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп нагрев.
        /// </summary>
        public static string StopHeating {
            get {
                return ResourceManager.GetString("StopHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп измерения.
        /// </summary>
        public static string StopMeasurement {
            get {
                return ResourceManager.GetString("StopMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТЧП.
        /// </summary>
        public static string TemperatureSensitiveParameter {
            get {
                return ResourceManager.GetString("TemperatureSensitiveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двухсторонее.
        /// </summary>
        public static string TwoWay {
            get {
                return ResourceManager.GetString("TwoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип устройства.
        /// </summary>
        public static string TypeDevice {
            get {
                return ResourceManager.GetString("TypeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим работы.
        /// </summary>
        public static string WorkingMode {
            get {
                return ResourceManager.GetString("WorkingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zth Длинный импульс.
        /// </summary>
        public static string ZthLongImpulse {
            get {
                return ResourceManager.GetString("ZthLongImpulse", resourceCulture);
            }
        }
    }
}
